@password=${$env PASSWORD}
@username={{$dotenv USERNAME}}
@email={{$dotenv GMAIL}}
@userId=4  # 👈 เปลี่ยนเป็น user id ที่ต้องการ

### Getting all users
GET http://localhost:8080/api/users

### Create api user
POST http://localhost:8080/api/auth/local/register
Content-Type: application/json

{
  "email": "{{email}}",
  "username": "{{username}}",
  "password": "{{password}}"
}

### Update user by ID
PUT http://localhost:8080/api/users/{{userId}}
Content-Type: application/json

{
    "username": "Kittithat Khunklangsaeng (Updated)",
    "email": "kittithat-kh-update@rmutp.ac.th"
}

### Delete user by ID
DELETE http://localhost:8080/api/users/{{userId}}