version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_db_kittithat
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
